export const textStyles = {
  'Heading/Desktop/Regular': { fontStyle: 'normal', fontWeight: 400, fontSize: '4xl' },
  'Heading/Desktop/SemiBold': { fontStyle: 'normal', fontWeight: 600, fontSize: '4xl' },
  'Heading/Desktop/Bold': { fontStyle: 'normal', fontWeight: 700, fontSize: '4xl' },
  'Heading/Tablet/Regular': { fontStyle: 'normal', fontWeight: 400, fontSize: '3xl' },
  'Heading/Tablet/SemiBold': { fontStyle: 'normal', fontWeight: 600, fontSize: '3xl' },
  'Heading/Tablet/Bold': { fontStyle: 'normal', fontWeight: 700, fontSize: '3xl' },
  'Heading/Mobile/Regular': { fontStyle: 'normal', fontWeight: 400, fontSize: '2xl' },
  'Heading/Mobile/SemiBold': { fontStyle: 'normal', fontWeight: 600, fontSize: '2xl' },
  'Heading/Mobile/Bold': { fontStyle: 'normal', fontWeight: 700, fontSize: '4xl' },
  'Large/Desktop/Regular': { fontStyle: 'normal', fontWeight: 400, fontSize: 'lg' },
  'Large/Desktop/SemiBold': { fontStyle: 'normal', fontWeight: 600, fontSize: 'lg' },
  'Large/Desktop/Bold': { fontStyle: 'normal', fontWeight: 700, fontSize: 'lg' },
  'Large/Tablet/Regular': { fontStyle: 'normal', fontWeight: 400, fontSize: 'lg' },
  'Large/Tablet/SemiBold': { fontStyle: 'normal', fontWeight: 600, fontSize: 'lg' },
  'Large/Tablet/Bold': { fontStyle: 'normal', fontWeight: 700, fontSize: 'lg' },
  'Large/Mobile/Regular': { fontStyle: 'normal', fontWeight: 400, fontSize: 'lg' },
  'Large/Mobile/SemiBold': { fontStyle: 'normal', fontWeight: 600, fontSize: 'lg' },
  'Large/Mobile/Bold': { fontStyle: 'normal', fontWeight: 700, fontSize: 'lg' },
};
